from fastapi import FastAPI, HTTPException
from ..schemas.models import (
    BusinessSnapshot,
    ExperimentPlan,
    VariantPlan,
    SampleSizeRules,
    CreativeVariant,
    RubricScore,
    ExperimentResult,
    VariantResult,
    NextTestRecommendation,
)

app = FastAPI(title="Agentic Ad Optimizer API")


@app.get("/")
def root():
    return {"message": "Welcome to the Agentic Ad Optimizer API"}


@app.post("/experiment-plan", response_model=ExperimentPlan)
def create_experiment_plan(snapshot: BusinessSnapshot):
    """Generate a simple experiment plan from a business snapshot."""
    plan = ExperimentPlan(
        experiment_id="exp_001",
        objective="Increase ROAS",
        hypothesis="New creative variants will outperform control",
        variants=[
            VariantPlan(variant_id="A", control=True, description="Control variant"),
            VariantPlan(variant_id="B", control=False, description="New creative variant B"),
            VariantPlan(variant_id="C", control=False, description="New creative variant C"),
        ],
        metrics=["ctr", "cpc", "cvr", "roas", "net_profit"],
        sample_size_rules=SampleSizeRules(
            min_spend_per_variant=200.0,
            min_conversions=50,
        ),
    )
    return plan


@app.post("/creative-variants", response_model=list[CreativeVariant])
def generate_creative_variants(plan: ExperimentPlan):
    """Generate dummy creative variants for each variant in an experiment plan."""
    creatives: list[CreativeVariant] = []
    for variant in plan.variants:
        creatives.append(
            CreativeVariant(
                variant_id=variant.variant_id,
                hook=f"Hook for {variant.description}",
                primary_text="This is an autogenerated ad copy.",
                headline="Try our product!",
                call_to_action="Buy Now",
            )
        )
    return creatives


@app.post("/score-creatives", response_model=list[RubricScore])
def evaluate_creatives(creatives: list[CreativeVariant]):
    """Assign dummy rubric scores to creatives."""
    scores: list[RubricScore] = []
    for creative in creatives:
        scores.append(
            RubricScore(
                creative_id=creative.variant_id,
                clarity_of_promise=4,
                emotional_resonance=3,
                proof_and_credibility=3,
                offer_and_risk_reversal=4,
                call_to_action_score=4,
                channel_fit=4,
                curiosity_hook_factor=3,
                overall_strength=3.5,
                feedback="This is a dummy feedback. Improve proof and credibility.",
            )
        )
    return scores


@app.post("/results", response_model=NextTestRecommendation)
def process_experiment_results(results: ExperimentResult):
    """Process experiment results and suggest next tests."""
    if not results.results:
        raise HTTPException(status_code=400, detail="No results provided")
    # determine winner by highest profit
    winner = max(results.results, key=lambda r: r.profit)
    recommendation = NextTestRecommendation(
        experiment_id=results.experiment_id,
        recommended_variants=[
            VariantPlan(variant_id="D", control=False, description="New creative variant D"),
            VariantPlan(variant_id="E", control=False, description="New creative variant E"),
        ],
        summary=f"Variant {winner.variant_id} performed best. Propose testing new variants.",
    )
    return recommendation
